### ISSUE TITLE
When is it going to be available?

### ISSUE THREAD

**Issue by aguinaldoabbj** [eren-ck/MultiscaleSnapshots#1]
I've read your very interesting paper. Would like to know when your research "product" will be available.

**Comment by eren-ck** [comment]
Hello, 
glad to hear that you are interested in the code to the paper. 

The project will be officially presented at the VIS in October. I will publish the code before the conference. Probably by the end of September. 

Cheers, 
Eren

**Comment by eren-ck** [comment]
Done.
