### ISSUE TITLE
Karate Club citation

### ISSUE THREAD

**Issue by benedekrozemberczki** [eren-ck/MultiscaleSnapshots#2]
Dear Authors,

You decided to use the Karate Club library because you most probably struggled to implement the whole graph embedding methods on your own. Yet you did not even care to cite the system design paper. I find this a pretty poor and unethical practice.

Best wishes,

Benedek Rozemberczki

**Comment by eren-ck** [comment]
Dear Benedek Rozemberczki, 
sorry to hear that. I am a fan of your work. I will add a reference to the preprint version of the paper and also a reference to the readme. 

Best Regards, 
Eren
