### ISSUE TITLE
how to generate embeddings using your library if my input is in grapson(json) or graphml(xml) format?

### ISSUE THREAD

**Issue by anushka192001** [eren-ck/MultiscaleSnapshots#5]
how to generate embeddings using your library if my input is in grapson(json) or graphml(xml) format?

**Comment by eren-ck** [comment]
Dear Anushka, 
you can read the dataset using networkX and you need to transform the dynamic graph to a list of graphs and than you can use the script to generate the embeddings. I hope that helps you. 

Cheers, 
Eren
